FROM haproxy:3.4-alpine@sha256:87fbdb208053937c1143bc3fa37e2a4001a9d9dc5d7e6b7f10d8bf15d4d8e794

LABEL maintainer="Thorsten Schifferdecker https://github.com/curx" \
  org.label-schema.vendor="Thorsten Schifferdecker" \
  org.label-schema.name="haproxy-k8scp" \
  org.label-schema.version="2.1" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["entrypoint.sh"]

RUN apk -U --no-cache add socat

COPY ./overlay ./overlay-amd64 /
